version: "3.4"

services:
  frontend:
    image: snymanc/swarm-demo-frontend:rpi-v8
    secrets:
      - pg_secret
    env_file:
      - app.env
    labels:
      app: demo
    deploy:
      replicas: 10
      update_config:
        failure_action: rollback
        parallelism: 3
        delay: 3s
        max_failure_ratio: 0.1
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 1
      placement:
        constraints:
          - node.labels.region==zar-jhb

  db:
    image: snymanc/swarm-demo-db:rpi-v1
    env_file:
      - db.env
    secrets:
      - pg_secret
    volumes:
      - pg-data:/var/lib/postgresql/data
    deploy:
      resources:
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.hostname == rpi1

  lb:
    image: snymanc/swarm-demo-lb:rpi-v1
    environment:
      - PROXY_UPSTREAM=frontend:8080
    ports:
      - 80:80
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

volumes:
  pg-data:

secrets:
  pg_secret:
    file: ./pg_secret
