version: "3.4"

services:
  frontend:
    image: snymanc/swarm-demo-frontend:rpi-v4
    secrets:
      - pg_secret
    env_file:
      - app.env
    deploy:
      replicas: 5
      update_config:
        failure_action: rollback
        parallelism: 3
        delay: 3s
        max_failure_ratio: 0.1

  db:
    image: postgres:9.6-alpine
    env_file:
      - db.env
    secrets:
      - pg_secret
    volumes:
      - pg-data:/var/lib/postgresql/data
    configs:
      - source: dcnf_create_table_sql
        target: /docker-entrypoint-initdb.d/create_table.sql
    deploy:
      resources:
        reservations:
          memory: 256M
      placement:
        constraints:
          - node.hostname == rpi1

  lb:
    image: snymanc/swarm-demo-lb:rpi-v1
    environment:
      - PROXY_UPSTREAM=frontend:8080
    ports:
      - 80:80
    deploy:
      replicas: 2

volumes:
  pg-data:

secrets:
  pg_secret:
    file: ./pg_secret

configs:
  create_table_sql:
    file: ../swarm-demo-db/create_table.sql
  dcnf_create_table_sql:
    external: true
