version: "3.4"

services:
  frontend:
    image: snymanc/swarm-demo-frontend:rpi-v7
    env_file:
      - config/app.env
    healthcheck:
      test: curl -f http://localhost:8080/status || false
      interval: 2s
      retries: 3
      start_period: 3s

  db:
    image: postgres:9.6-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - config/db.env

  lb:
    image: snymanc/swarm-demo-lb:rpi-v1
    environment:
      - PROXY_UPSTREAM=frontend:8080
    ports:
      - 80:80
